# Generated by Django 5.2 on 2025-05-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='single_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_date', models.DateField(auto_now=True)),
                ('start_time', models.TimeField(auto_now=True)),
                ('end_time', models.TimeField(auto_now=True)),
                ('break_time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('job_name', models.CharField(max_length=100)),
                ('user_notes', models.TextField()),
            ],
        ),
    ]
