# Generated by Django 5.2 on 2025-05-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoursCalc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='single_day',
            name='day_hours',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
