# Generated by Django 5.2 on 2025-05-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoursCalc', '0002_single_day_day_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_day',
            name='break_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='single_day',
            name='day_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='single_day',
            name='day_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='single_day',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='single_day',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='single_day',
            name='user_notes',
            field=models.TextField(blank=True),
        ),
    ]
